sort00: sort00.cc
	g++ -std=c++11 -o sort00 sort00.cc

vector00: vector00.cc
	g++ -std=c++11 -o vector00 vector00.cc

vector01: vector01.cc
	g++ -std=c++11 -o vector01 vector01.cc

vector02: vector02.cc
	g++ -std=c++11 -o vector02 vector02.cc

vector03: vector03.cc
	g++ -std=c++11 -o vector03 vector03.cc

vector04: vector04.cc
	g++ -std=c++11 -o vector04 vector04.cc

all: sort00 vector00 vector01 vector02 vector03 vector04

clean:
	rm -rf sort00 vector00 vector01 vector02 vector03 vector04
